### ISSUE TITLE
./run_experiment fails near-silently when network connection to Host PC is not detected

### ISSUE THREAD

**Issue by dunadan67** [ramdarpaprojectorg/RAMControl#18]
If there is no network connection to the host PC, or more problematically, the network cable is connected but for some reason the mac doesn't detect the connection, when the user executes run_experiment, the terminal window will just disappear with no feedback as to what the issue was.

**Comment by mivade** [comment]
It's not silent, you're just not reading fast enough!

**Comment by dunadan67** [comment]
Yeah I suggested to some of our users to run the script from the command line instead, so the terminal window doesn't just vanish, but they tend to run experiments by double-clicking the script (out of habit).

**Comment by mivade** [comment]
Please refer them to [the troubleshooting section of the README](https://github.com/ramdarpaprojectorg/RAMControl#troubleshooting). It would be easy to add something so that the window stays open until there is user input, but the "debug mode" is a good thing to know about anyway for troubleshooting.

**Comment by dunadan67** [comment]
Good point, I'll pass it along.
