### ISSUE TITLE
FR is using identical word lists for each session

### ISSUE THREAD

**Issue by dunadan67** [ramdarpaprojectorg/RAMControl#21]
Confirmed with R1299T and R1293P.  FR1 is using identical word lists for each session (look at the session.log files).

**Comment by mivade** [comment]
Fixed in v3.1.7.

This is a perfect example of why we need to move away from PyEPL. The list generation is unit tested, but there is no way of unit testing stuff involving PyEPL (believe me, I've tried, and it doesn't even run the tests because PyEPL does all sorts of naughty things that crash test runners).
